### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by Blisk** [psi-4ward/psitransfer#188]
I am not quite familliar with this npm so I need a bit help.
I have installed psitransfer on my web server but I get nothing when I try
I did this to install on centos 7.9
Manual

You need to have Node.js version >= 7.4 and npm installed.

1.) Download and extract a prebuild PsiTransfer release from GitHub

2.) Install the dependencies: npm install --production

3.) Run the app: npm start
Linux Systemd service

You can also install PsiTransfer as (Linux) system service. Most distributions use Systemd as main init system. You should not run PsiTransfer with root privileges!

Preparation

# Create a target folder for PsiTransfer
mkdir -p /opt/psitransfer
cd /opt/psitransfer

# Download and extract a prebuild
curl -sL https://github.com/psi-4ward/psitransfer/releases/download/1.1.0-beta/psitransfer-1.1.0-beta.tar.gz | tar xz --strip 1

# Install dependencies
npm install --production

# Add a user psitransfer
sudo useradd --system psitransfer

# Make psitransfer owner of /opt/psitransfer
sudo chown -R psitransfer:psitransfer /opt/psitransfer

Systemd unit file

Grab the psitransfer.service sample file, put it in /etc/systemd/system/ and adjust to your needs.

cd /etc/systemd/system
sudo wget https://raw.githubusercontent.com/psi-4ward/psitransfer/master/docs/psitransfer.service

# Start the service
sudo systemctl start psitransfer

# Show the status
sudo systemctl status psitransfer

# Enable autostart on boot
sudo systemctl enable psitransfer

**And now I have error when npm start**
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@4.2.0
3 info using node@v7.10.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle psitransfer@2.0.1~prestart: psitransfer@2.0.1
6 silly lifecycle psitransfer@2.0.1~prestart: no script for prestart, continuing
7 info lifecycle psitransfer@2.0.1~start: psitransfer@2.0.1
8 verbose lifecycle psitransfer@2.0.1~start: unsafe-perm in lifecycle true
9 verbose lifecycle psitransfer@2.0.1~start: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/opt/psitransfer/node_modules/.bin:/usr/local/rvm/gems/ruby-2.3.0/bin:/usr/local/rvm/gems/ruby-2.3.0@global/bin:/usr/local/rvm/rubies/ruby-2.3.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/usr/local/rvm/bin:/root/bin
10 verbose lifecycle psitransfer@2.0.1~start: CWD: /opt/psitransfer
11 silly lifecycle psitransfer@2.0.1~start: Args: [ '-c', 'NODE_ENV=production node app.js' ]
12 silly lifecycle psitransfer@2.0.1~start: Returned: code: 1  signal: null
13 info lifecycle psitransfer@2.0.1~start: Failed to exec start script
14 verbose stack Error: psitransfer@2.0.1 start: `NODE_ENV=production node app.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:194:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:194:7)
14 verbose stack     at maybeClose (internal/child_process.js:899:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid psitransfer@2.0.1
16 verbose cwd /opt/psitransfer
17 error Linux 3.10.0-1160.42.2.el7.x86_64
18 error argv "/usr/bin/node" "/usr/bin/npm" "start"
19 error node v7.10.1
20 error npm  v4.2.0
21 error code ELIFECYCLE
22 error errno 1
23 error psitransfer@2.0.1 start: `NODE_ENV=production node app.js`
23 error Exit status 1
24 error Failed at the psitransfer@2.0.1 start script 'NODE_ENV=production node app.js'.
24 error Make sure you have the latest version of node.js and npm installed.
24 error If you do, this is most likely a problem with the psitransfer package,
24 error not with npm itself.
24 error Tell the author that this fails on your system:
24 error     NODE_ENV=production node app.js
24 error You can get information on how to open an issue for this project with:
24 error     npm bugs psitransfer
24 error Or if that isn't available, you can get their info via:
24 error     npm owner ls psitransfer
24 error There is likely additional logging output above.
25 verbose exit [ 1, true ]

**Comment by Blisk** [comment]
Can anyone help me?
