### ISSUE TITLE
build / start error

### ISSUE THREAD

**Issue by codingyannick** [psi-4ward/psitransfer#33]
Here is my Error-message

```
psitransfer-1.2.0$ npm start

> psitransfer@1.0.0 start /var/www/html/webapps/psitransfer-1.2.0
> NODE_ENV=production node app.js

/var/www/html/webapps/psitransfer-1.2.0/lib/endpoints.js:117
app.get('/files/:fid', async(req, res, next) => {
                            ^
SyntaxError: Unexpected token (
    at Object.exports.runInThisContext (vm.js:78:16)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/var/www/html/webapps/psitransfer-1.2.0/app.js:3:13)
    at Module._compile (module.js:571:32)

npm ERR! Linux 4.4.0-93-generic
npm ERR! argv "/var/www/.nvm/versions/node/v7.4.0/bin/node" "/var/www/.nvm/versions/node/v7.4.0/bin/npm" "start"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! psitransfer@1.0.0 start: `NODE_ENV=production node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the psitransfer@1.0.0 start script 'NODE_ENV=production node app.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the psitransfer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     NODE_ENV=production node app.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs psitransfer
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls psitransfer
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/html/webapps/psitransfer-1.2.0/npm-debug.log
```

**Comment by psi-4ward** [comment]
This is solved, isn't it?
