### ISSUE TITLE
Failed to start

### ISSUE THREAD

**Issue by BirkHappens** [psi-4ward/psitransfer#49]
`[nbirkley@ip-172-31-39-58 psitransfer-1.2.0]$ sudo npm start

> psitransfer@1.0.0 start /usr/share/nginx/html/psitransfer-1.2.0
> NODE_ENV=production node app.js

/usr/share/nginx/html/psitransfer-1.2.0/lib/endpoints.js:117
app.get('/files/:fid', async(req, res, next) => {
                            ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/share/nginx/html/psitransfer-1.2.0/app.js:3:13)

npm ERR! Linux 3.10.0-693.21.1.el7.x86_64
npm ERR! argv "/usr/bin/node" "/bin/npm" "start"
npm ERR! node v6.14.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! psitransfer@1.0.0 start: `NODE_ENV=production node app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the psitransfer@1.0.0 start script 'NODE_ENV=production node app.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the psitransfer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     NODE_ENV=production node app.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs psitransfer
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls psitransfer
npm ERR! There is likely additional logging output above.
`

On npm start I'm getting a weird error.  Any suggestions? Looks like another user had this issue, but the ticket was closed without explanation.

Thanks!

**Comment by psi-4ward** [comment]
you just need a newer version of NodeJS
